Strange error.
Sometimes need to migrate twice so that the test code can work properly...
Though there still may have the following "Error" showing up, after all the tests pass...

C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:213982
        throw reason;
        ^

Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:37295:16)
    at C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:224765:36
    at C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (C:\Users\qianc\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67535:24)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)